# The URL to the MPD server you wish to monitor
MPDServerURL = "localhost:6600"

# The path to the MPD server's music -- this should be accessible
# somehow over your local machine.
MusicDirectory = "~/Music"

# How long the notification should persist, in milliseconds
PopupTimeout = 5000

# The icon to display if there is no album art associated with the
# music in question
DefaultIcon = "~/.config/mpdnotify/music-note.svg"